src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GMT_Offset__c</fullName>
        <label>GMT Offset</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_zone_display_name__c</fullName>
        <label>Time zone display name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GMT_Offset__c</fullName>
        <label>GMT Offset</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_zone_display_name__c</fullName>
        <label>Time zone display name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/TestUtil.cls
public with sharing class TestUtil {

    public static void checkFields(Account acc) {
        System.assertEquals('UA', acc.Country_Code__c);
        System.assertEquals(2, acc.GMT_Offset__c);
        System.assertEquals('Eastern European Standard Time', acc.Time_zone_display_name__c);
    }

    public static void checkFields(Lead l) {
        System.assertEquals('UA', l.Country_Code__c);
        System.assertEquals(2, l.GMT_Offset__c);
        System.assertEquals('Eastern European Standard Time', l.Time_zone_display_name__c);
    }

    public static Account createTestAccount() {
        return new Account(Name='Test account', BillingLatitude=50.460225, BillingLongitude=30.622090);
    }

    public static Opportunity createTestOpportunity() {
        return new Opportunity(Name='Test Opportunity',
                StageName='Qualification',
                CloseDate=Date.newInstance(2030, 12, 31));
    }

    public static Lead createTestLead() {
        return new Lead(LastName='Test Lead', Company='Test company');
    }
}