src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Local_Time_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Local Time Setting</label>
        <referenceTo>Account_Local_Time_Setting__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Local_Time_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Use_12_Hour_Format__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Use 12 Hour Format</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Geolocation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Geolocation</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Local Time Setting</label>
    <nameField>
        <label>Account Local Time Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Local Time Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Local_Time_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Local Time Setting</label>
        <referenceTo>Lead_Local_Time_Setting__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Lead_Local_Time_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Use_12_Hour_Format__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Use 12 Hour Format</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Geolocation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Geolocation</label>
        <type>Checkbox</type>
    </fields>
    <label>Lead Local Time Setting</label>
    <nameField>
        <label>Lead Custom Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Local Time Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Use_12_Hour_Format__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Use 12 Hour Format</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Geolocation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Geolocation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Local_Time_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Use_12_Hour_Format__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Use 12 Hour Format</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Geolocation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Geolocation</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity Local Time Setting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Opportunity Local Time Setting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Local Time Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectManager.cls
public class ObjectManager {

	private static final ObjectManager INSTANCE = new ObjectManager();

	public static ObjectManager getInstance() {
		return INSTANCE;
	}

	public Account getAccount(Id accountId) {
		return [SELECT Id, BillingLatitude, BillingLongitude FROM Account WHERE Id = : accountId LIMIT 1];
	}

	public Opportunity getOpportunity(Id opportunityId) {
		List<Opportunity> opportunities = [SELECT Account_Local_Time_Setting__c, AccountId
										   FROM Opportunity
										   WHERE Id =: opportunityId
										   LIMIT 1];
		if (opportunities.size() == 1) {
			return opportunities.get(0);
		}

		return null;
	}

	public Lead getLead(Id leadId) {
		List<Lead> leads = [SELECT Lead_Local_Time_Setting__c, Latitude, Longitude
							FROM Lead
							WHERE Id =: leadId
							LIMIT 1];
		if (leads.size() == 1) {
			return leads.get(0);
		}

		return null;
	}

	public Opportunity_Local_Time_Setting__c getOpportunitySetting(Id settingId) {
		return [SELECT Use_12_Hour_Format__c, Use_Geolocation__c
				FROM Opportunity_Local_Time_Setting__c
				WHERE Id =: settingId
				LIMIT 1];
	}

	public Lead_Local_Time_Setting__c getLeadSetting(Id settingId) {
		return [SELECT Use_12_Hour_Format__c, Use_Geolocation__c
				FROM Lead_Local_Time_Setting__c
				WHERE Id =: settingId
				LIMIT 1];
	}
}